name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: prepare Node.js ${{ matrix.node-version }}
      run: |
        npm install babel-preset-typescript    
        npm install scss
        npm install @stencil/core
        npm ci
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    if: github.ref == 'refs/heads/main'
    steps:
    - run : npm install
    - uses : actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - name : delivery prep
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@vetrify'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}