name: Node.js CI

on:
  push:
    branches: [main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@vetrify'
    - run: npm install babel-preset-typescript    
    - run: npm install scss
    - run: npm install @stencil/core
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    #if: github.ref == 'refs/heads/main'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}