name: Vetrify CI

on:
  push:
    branches: [main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: install - Node.js ${{ matrix.node-version }}
      run: npm install
    - name: test
      run: npm test --max-old-space-size=8192 --no-warnings

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    if: github.ref == 'refs/heads/main'
    steps:
    # Setup .npmrc file to publish to GitHub Packages
    - name : delivery prep
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@vetrify'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}