name: Node.js CI

on:
  push:
    branches: [main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        npm install babel-preset-typescript    
        npm install scss
        npm install @stencil/core
    - name: build
      run: |
        npm ci
        npm run build --if-present
    - name: test
      run: npm test
        # Setup .npmrc file to publish to GitHub Packages
    - name : deliver
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@vetrify'
    #if: github.ref == 'refs/heads/main'
      run: |
        npm install
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}